# Generated by Django 5.2.1 on 2025-06-03 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='pdf_task_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='pdf_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
