# Generated by Django 5.2.1 on 2025-06-03 19:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customer_invoice_logo_invoice_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg'])]),
        ),
    ]
