# Generated by Django 5.2.1 on 2025-06-03 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_invoice_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='pdf_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='pdf_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='pdf_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['created_at'], name='api_invoice_created_2ecffa_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['customer'], name='api_invoice_custome_23f78b_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['pdf_generated_at'], name='api_invoice_pdf_gen_f4d270_idx'),
        ),
    ]
