# Generated by Django 5.2.1 on 2025-06-04 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_invoice_pdf_filename_invoice_pdf_generated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='pdf_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['pdf_status'], name='api_invoice_pdf_sta_720b9a_idx'),
        ),
    ]
