# Generated by Django 5.2.1 on 2025-06-04 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_invoice_pdf_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='api_invoice_pdf_gen_f4d270_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='api_invoice_pdf_sta_720b9a_idx',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='pdf_filename',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='pdf_generated_at',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='pdf_size',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='pdf_status',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='pdf_task_id',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='pdf_updated_at',
        ),
        migrations.AddField(
            model_name='taskstatus',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='api.invoice'),
        ),
        migrations.AddIndex(
            model_name='taskstatus',
            index=models.Index(fields=['status'], name='api_tasksta_status_80b58c_idx'),
        ),
        migrations.AddIndex(
            model_name='taskstatus',
            index=models.Index(fields=['invoice'], name='api_tasksta_invoice_c83c13_idx'),
        ),
        migrations.AddIndex(
            model_name='taskstatus',
            index=models.Index(fields=['created_at'], name='api_tasksta_created_3d77f0_idx'),
        ),
    ]
