# Generated by Django 5.2.1 on 2025-06-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_taskstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstatus',
            name='heartbeat_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
