# Generated by Django 5.2.1 on 2025-06-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_taskstatus_heartbeat_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskstatus',
            name='task_id',
            field=models.CharField(max_length=100),
        ),
    ]
