# Generated by Django 5.2.1 on 2025-06-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_invoice_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='pdf_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
